### ISSUE TITLE
Support Bot API v3.0

### ISSUE THREAD

**Issue by GochoMugo** [yagop/node-telegram-bot-api#332]
* New kinds of updates (https://core.telegram.org/bots/api#update):
  * [x] `shipping_query` (prs: #333)
  * [x] `pre_checkout_query` (prs: #333)
* New types of message content (https://core.telegram.org/bots/api#message):
  * [x] `invoice` (prs: #333)
  * [x] `successful_payment` (prs: #333)
  * [x] `video_note` (commits: https://github.com/yagop/node-telegram-bot-api/commit/73269e79e29fe51ebed20d8a15ae80a83778130f)
* New methods:
  * [x] `sendInvoice` (https://core.telegram.org/bots/api#sendinvoice) (prs: #335)
  * [x] `answerShippingQuery` (https://core.telegram.org/bots/api#answershippingquery) (prs: #335)
  * [x] `answerPreCheckoutQuery` (https://core.telegram.org/bots/api#answerprecheckoutquery) (prs: #335)
  * [x] `sendVideoNote` (https://core.telegram.org/bots/api#sendvideonote) (prs: #330)
  * [x] `deleteMessage` (https://core.telegram.org/bots/api#deletemessage) (prs: #324)

Already supported:

* New type of button, the pay button to `InlineKeyboardButton`
* Fields `record_video_note`,  `upload_video_note` for `sendChatAction` method
* `language_code` field in `User` object  that contains the IETF language tag of the user's language
* `unbanChatMember` method works in channels
* Replaced the field `new_chat_member` in Message with `new_chat_members`
* Inline keyboards with `switch_inline_query` and `switch_inline_query_current_chat` can no longer be sent to channels
* New fields `gif_duration` in `InlineQueryResultGif` and `mpeg4_duration` in `InlineQueryResultMpeg4Gif`

**Comment by kamikazechaser** [comment]
PR #330 addresses the new `sendVideoNote` method. However, there seems to be an issue with the Telegram documentation regarding this method, which doesn't state that length is actually a required parameter.

**Comment by aaaee2** [comment]
The `language_code` field is present in the User object, when application is running on the win32 platform, but not in linux.

**Comment by kamikazechaser** [comment]
PR #333 addresses the new update types and message sub-types. It also addresses missing/renamed message sub-types.

**Comment by kamikazechaser** [comment]
Commit 959d7bf addresses the new `deleteMessage` method.

**Comment by kamikazechaser** [comment]
@aaaee2 I don't get the issue on my side. In fact, the issue cannot be caused by the library since it returns an unadulterated object from Telegrams update.

**Comment by kamikazechaser** [comment]
Due to many required options in `sendInvoice` method, it would be better to form an object containg the options, something like: 

```js
  bot.sendInvoice(chatId, {
    title: "Test",
    decription: "test description",
    payload: "test payload",
    provider_token: "Token",
    start_parameter: "Param",
    currency: "USD",
    prices: [
      { label: "Part A", amount: 100},
      { label: "Part B", amount: 200},      
    ]
  });
```

What do you think, @GochoMugo ?

**Comment by GochoMugo** [comment]
@kamikazechaser Let's just stay consistent. Let the object be for *optional* parameters.

**Comment by kamikazechaser** [comment]
PR #335 address all new payment methods.

**Comment by kamikazechaser** [comment]
@GochoMugo I think we can review and merge.

**Comment by Lord-Protector** [comment]
So what we wait? :) Code looks great.

**Comment by sheshvs** [comment]
Hi, Thanks for all the work you guys are doing to maintain this repository active. Was planning to use some of the features of BotAPI v3.0. Just wanted to know when is the next release planned with the above code.
Thanks again!.

**Comment by Lord-Protector** [comment]
@GochoMugo Why it's not on NPM yet? Already Bot API v3.1 has been released.

**Comment by GochoMugo** [comment]
@Lord-Protector Let me consult @yagop on that. You can alway use the `master` branch from Github i.e. `npm install yagop/node-telegram-bot-api#master`, but I would **not** recommend it for production environments.

**Comment by GochoMugo** [comment]
**New Release, v0.28.0 :confetti_ball:**
